
spring:
  profiles:
    active: dev

server:
  port: 8090

#logging:
#  level:
#    com:
#      jt: trace
#  pattern:
##       日志输出格式：
##   		%d表示日期时间，
##   		%thread表示线程名，
##   		%-5level：级别从左显示5个字符宽度
##   		%logger{50} 表示logger名字最长50个字符，否则按照句点分割。
##   		%msg：日志消息，
##   		%n是换行符
#    file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n'
#    console: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n'
#  path: ./logs


person:
  lastName: tangjingtai
  age: 29
  boss: true
  maps:
    k1: 1
    k2: hello
  list:
   - 1
   - 2
   - 3
  dog:
    name: dog
    age: 2
  birth: 1990/10/04
  email: a253210810@qq.com


---
spring:
  profiles: dev
server:
  port: 8091


---
spring:
  profiles: prod
server:
  port: 80
