spring:
  application:
    name: oauth2-content

server:
  port: 8901
  servlet:
    context-path: /content

security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
      access-token-uri: http://localhost:8900/oauth/token
      user-authorization-uri: http://localhost:8900/oauth/authorize
    resource:
      token-info-uri: http://localhost:8900/oauth/check_token